version: '2'

services:
  proxy:
    image: kuzzleio/proxy
    ports:
      - "7511-7513:7511-7513"

  kuzzle:
    image: kuzzleio/kuzzle
    depends_on:
      - proxy
      - redis
      - elasticsearch
    environment:
      - kuzzle_services__db__host=elasticsearch
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - kuzzle_services__proxyBroker__host=proxy
      - NODE_ENV=production
      - kuzzle_plugins__kuzzle-plugin-template__path=/tmp/kuzzle-plugin-template
      - kuzzle_plugins__kuzzle-plugin-template__activated=true
      - kuzzle_plugins__kuzzle-plugin-template__version=
    volumes:
      - '../:/tmp/kuzzle-plugin-template'
      - './pm2.json:/config/pm2.json'

  redis:
    image: redis:3.2

  elasticsearch:
    image: elasticsearch:5.0
