version: '2.1'

services:
  proxy:
    image: kuzzleio/proxy${PROXY_DOCKER_TAG}
    ports:
      - "7511-7513:7511-7513"

  kuzzle:
    image: kuzzleio/kuzzle${KUZZLE_DOCKER_TAG}
    volumes:
      - "./pm2.json:/config/pm2.json"
      - "..:/var/app/plugins/enabled/${PLUGIN_NAME:-kuzzle_plugin_template}"
    depends_on:
      - proxy
      - redis
      - elasticsearch
    ports:
      - "8080:8080"
      - "9229:9229"
    environment:
      - kuzzle_services__db__host=elasticsearch
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - kuzzle_services__proxyBroker__host=proxy
      - NODE_ENV=development
      - DEBUG=kuzzle:plugins
  redis:
    image: redis:3.2

  elasticsearch:
    image: elasticsearch:5.0
