version: '2.1'

services:
  proxy:
    image: kuzzleio/proxy${PROXY_DOCKER_TAG}
    ports:
      - "7512:75123"

  kuzzle:
    image: kuzzleio/kuzzle${KUZZLE_DOCKER_TAG}
    volumes:
      - "./pm2.json:/config/pm2.json"
      - "..:/var/app/plugins/enabled/${PLUGIN_NAME:-kuzzle-core-plugin-boilerplate}"
    depends_on:
      - proxy
      - redis
      - elasticsearch
    ports:
      - "8080:8080"
      - "9229:9229"
    environment:
      - kuzzle_services__db__host=elasticsearch
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - kuzzle_services__proxyBroker__host=proxy
      - NODE_ENV=development
      - DEBUG=kuzzle:plugins

  redis:
    image: redis:3.2

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    environment:
      - cluster.name=kuzzle
      # disable xpack
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
