version: '2'

services:
  proxy:
    image: kuzzleio/proxy:develop
    ports:
      - "7511-7513:7511-7513"

  kuzzle:
    build: kuzzle
    volumes:
      - "./refresh.sh:/tmp/refresh.sh"
      - "./pm2.json:/config/pm2.json"
      - "..:/tmp/kuzzle-plugin-dev"
    depends_on:
      - proxy
      - redis
      - elasticsearch
    ports:
      - "8080:8080"
      - "9229:9229"
    environment:
      - kuzzle_services__db__host=elasticsearch
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - kuzzle_services__proxyBroker__host=proxy
      - NODE_ENV=development
      # If you change the plugin name in package.json, you must change it
      # on the next 3 lines.
      - kuzzle_plugins__kuzzle-plugin-template__path=/tmp/kuzzle-plugin-dev
      - kuzzle_plugins__kuzzle-plugin-template__version=
      - kuzzle_plugins__kuzzle-plugin-template__activated=true

  redis:
    image: redis:3.2

  elasticsearch:
    image: elasticsearch:5.0
